### ISSUE TITLE
link for 20A.EU2 broken + D614G not featured?

### ISSUE THREAD

**Issue by tuspjo** [hodcroftlab/covariants#124]
Hi, 
Thank you making this great resource. 

I noticed that the link for the 20A.EU2 seems to not work for me on chrome or firefox, maybe something broke?
https://covariants.org/variants/20A.EU2     "An unexpected error has occurred."

D614G is not on the mutations list, is this because it's so dominating? I think for example A.23.1 does not have D614G, why it could be relevant to report for the ones which have it? 

Kind regards, 

Tue

**Comment by emmahodcroft** [comment]
Oh Dear - thank you for catching this! The destruction that a missing `/` can cause...
I'm in the process of pushing up a fix for this now!

**Comment by emmahodcroft** [comment]
With regards to D614G - yes, I don't have this included because it's so widespread. I'm not sure a focal build on 614 would help this - it would just be 'too full' to be helpful. 
But I am hoping to add A.23.1 and some of the related '19B' variants soon, so that this is highlighted a little better!

**Comment by emmahodcroft** [comment]
This should be fixed now!
