### ISSUE TITLE
Pure relative provenance of variants

### ISSUE THREAD

**Issue by Toerag1** [hodcroftlab/covariants#139]
It would be useful to have graphs which show the relative prevalence of variants only and not the case volume as the case volume distorts the changes in relative prevalence.

**Comment by emmahodcroft** [comment]
Hi @Toerag1 thanks for your comment. Could you expand a little on what you mean here? 

The graphs as they currently are show the fraction of sequences by week ('Per Cluster') or two weeks ('Per Country') and are not scaled by cases in any way.

**Comment by emmahodcroft** [comment]
Hi @Toerag1 I'm going to close this issue as I'm not sure what you're requesting. Feel free to reopen and add more detail if you like.

**Comment by Toerag1** [comment]
Apologies for not responding sooner - I thought the grey areas at the top of the graphs were free space, I subsequently realised they're un-sequenced infections, sorry!

**Comment by emmahodcroft** [comment]
Ah - the grey area is sequences - it's just that they don't fall within any of the variants that I currently track on Covariants. I hope that clarifies though!
