### ISSUE TITLE
maybe error in description of 20J/501Y.V3 (P.1) 417T listed as 417N

### ISSUE THREAD

**Issue by tuspjo** [hodcroftlab/covariants#142]
Hi, I think that in the description of 20J/501Y.V3 (P.1), the K417T is listed as K417N, in this sentence: 
"501Y.V3 is associated with multiple mutations in Spike. Notably: S:N501Y (see MutationS:N501), S:E484K (see VariantS:E484).
But also S:L18F, S:K417N and S:H655Y."

**Comment by emmahodcroft** [comment]
Thank you for catching this - you're right!

**Comment by emmahodcroft** [comment]
@tuspjo I've incorporated this into what'll go live at the next push - do you have a Twitter username? I'd love to credit your fix!

**Comment by tuspjo** [comment]
cool, thanks.
my twitter handle is @tuesparholt

Best

Tue

Den søn. 25. apr. 2021 kl. 15.03 skrev Emma Hodcroft <
***@***.***>:
