### ISSUE TITLE
Croatia plot not displaying correctly

### ISSUE THREAD

**Issue by emmahodcroft** [hodcroftlab/covariants#146]
Croatia plot shows 'white spaces'. 
![image](https://user-images.githubusercontent.com/14290674/116427304-32e45780-a844-11eb-840f-0d39710ce298.png)

Mousing over the graph displays counts, which seem to correspond correctly, to the [per country counts](https://github.com/hodcroftlab/covariants/blob/master/web/data/perCountryData.json). So I think this may be a graphical bug. Perhaps because sometimes the number of sequences is so small, the smoothing is messing up?

**Comment by ivan-aksamentov** [comment]
I could not reproduce it on either `master` or `release` branch, and production deployment does not have it either.

It seems that only the branch `feat/better-defining-muts` (PR https://github.com/hodcroftlab/covariants/pull/145) is affected, specifically, the commit d73bacc61c62818522f972782a4d61071d0980bf.

I merged `origin/master` to `feat/better-defining-muts` and now it seems to be gone. Please confirm that it now works as intended for you.

**Comment by emmahodcroft** [comment]
Yea, that's super weird, because I am pretty sure I was seeing this on master, but it's gone for me now. Very odd. Anyway, if it's fixed it's fixed, and I'll keep an eye on it!

**Comment by emmahodcroft** [comment]
Ok for me this bug is appearing and disappearing - this is super weird.

CoVariants.org (release) - all country view, scrolled down:
![image](https://user-images.githubusercontent.com/14290674/116520029-7ab1c000-a8d2-11eb-9424-f1e69d3161d6.png)


CoVariants.org (release) filtering to show Croatia only for a better screenshot:
![image](https://user-images.githubusercontent.com/14290674/116520090-8c936300-a8d2-11eb-9d69-b3573779601c.png)

I can switch between these two views and make the white appear and disappear.

**Comment by ivan-aksamentov** [comment]
Not sure what happens here... Is it always the same color that drops out? Any messages in the console?

**Comment by emmahodcroft** [comment]
Don't know how, but I can't replicate this bug anymore, so I'll close the issue. Please do reopen or comment if anyone spots it again.
