### ISSUE TITLE
Any way to download VCF files for strains?

### ISSUE THREAD

**Issue by mhorlacher** [hodcroftlab/covariants#156]
Beautiful resources, thanks a lot!

However, I was wondering whether it is possible to download the set of strain-defining mutations for each strain as a VCF file? This would be it significantly easier to process computationally. 

Best

**Comment by emmahodcroft** [comment]
Hi @mhorlacher !

You can see the information that's turned into the list of 'defining mutations' on the right-hand side the page for each variant in the `clusters.py` file: https://github.com/hodcroftlab/covariants/blob/master/scripts/clusters.py

Alternatively, I'm hoping to soon introduce a more computationally processable file - you can see an example (incomplete) on the branch here: https://github.com/hodcroftlab/covariants/blob/covariants_file/covariants_objects.json

However, there's currently no plans to put this into a VCF file - considering how small the viral genomes are and how relatively un-diverse they are, I'm not sure there's much of a savings here.
