### ISSUE TITLE
Pango & common names

### ISSUE THREAD

**Issue by willo0o0o0** [hodcroftlab/covariants#161]
Add a little table translating the variant names on each page or somehow make this easily available for those wishing to post a link to a single page or graph.  This is great. Thanks.

**Comment by emmahodcroft** [comment]
Hi @willo0o0o0 - thanks for the idea! It would be neat to have a way to pin the translation table, I agree. Unfortunately at the moment I'm not sure how we'd work this in functionally or graphically - but we can definitely keep it in mind!
