### ISSUE TITLE
Design collaboration

### ISSUE THREAD

**Issue by richardgoater** [hodcroftlab/covariants#166]
Hi folks! I saw @emmahodcroft's presentation at the EBI symposium today and I realised I meant to get in touch a while ago.

I'm working on the front-end of [covid19.sanger.ac.uk](covid19.sanger.ac.uk) and I think it would be really cool to collaborate. I see you're also contending with Recharts for example, I'm sure we have common issues. Our visualisation code is [here](https://github.com/theosanderson/covince) and looks like you know @theosanderson.

If I may, I'd like to show you some design explorations I took the small liberty of doing a while back: https://www.figma.com/proto/qUwhDqxigIYlNLog1kvJLU/CoVariants?node-id=34%3A268&scaling=scale-down-width&page-id=0%3A1. First one is a variation on the existing theme, and the second is bringing a bit more Nextstrain across. Feel free to use anything from these :)

In any case it would be great to chat, think we could help each other out.

All the best,
Rich

**Comment by emmahodcroft** [comment]
Hi @richardgoater - and nice to meet you! I'd definitely be happy to chat about ideas and collaborations! In particular, I think there's a possibility of surfacing some more information if we add some elements to make things more interactive. I could chat sometime next week if that might work for you?

**Comment by richardgoater** [comment]
Hi @emmahodcroft, thanks so much! Next week works for me, let's arrange offline. Do you mind pinging a message to richard[dot]goater[at]sanger[dot]ac[dot]uk?
