### ISSUE TITLE
Direct links to sub-pages don't work

### ISSUE THREAD

**Issue by chaoran-chen** [hodcroftlab/covariants#170]
Hi. I can't access the sub-pages of CoVariants when I open them directly from their link (or if I refresh the browser when I am already on them). But it works if I start from the homepage and navigate to them using the menu buttons.

https://covariants.org/faq shows:

![image](https://user-images.githubusercontent.com/18666552/122195194-6c296300-ce96-11eb-9106-97a209867a54.png)

**Comment by ivan-aksamentov** [comment]
Hi @chaoran-chen,

Sorry about that. This is due to server misconfiguration. I will fix it soon.

Meanwhile, as a workaround, a link should work if you append `.html` to it:
```
https://covariants.org/faq.html
```

**Comment by ivan-aksamentov** [comment]
Should be fixed now. If not, please comment or open another issue.

**Comment by emmahodcroft** [comment]
Hi @chaoran-chen - just to let you know - this is my fault as I've been behind in getting the master file working, but the names of some of the pages are about to change as part of the update to start incorporating the WHO names. We'll implement redirects but to save users time it might be worth updating the links accordingly. I can try to remember to let you know when this goes through!

**Comment by chaoran-chen** [comment]
Thanks, @emmahodcroft! I will gladly update the links on cov-spectrum once the changes were made.
