### ISSUE TITLE
Use build_name  for filenames for consistency

### ISSUE THREAD

**Issue by ivan-aksamentov** [hodcroftlab/covariants#18]
We transited to `cluster.build_name` (as in `scripts/clusters.py`) for content (`.md`) filenames (see https://github.com/hodcroftlab/covariants/commit/f76f6aa9ec443108109dd2b668204121bfd75a29), but other places might still use `display_name`. 

Notably `.gif` images and `.jpg` stulls created from them are using `display_name`.

We might change that for:
 - consistency (confusing and error prone when adding new content)
 - better compat with Windows (which apparently still has problems with colons in filenames in 2021)
by using `build_name` instead.

**Comment by theosanderson** [comment]
Can confirm that I'm unable to clone the repo on windows

(kudos for all the amazing work)

**Comment by emmahodcroft** [comment]
Oh dear!

**Comment by theosanderson** [comment]
:) For info despite these fixes, building on Windows still wasn't possible for me. I got to:
```
$ cross-env NODE_ENV=development BABEL_ENV=development NODE_OPTIONS=--max_old_space_size=8192 babel-node --extensions ".js,.ts" -- node_modules/.bin/next dev --hostname 0.0.0.0 --port 3000
C:\Users\Theo\cov2\cluster_scripts\web\node_modules\.bin\next:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

Presumably it's expecting to be run from bash. I'm not saying supporting Windows ought to be a big priority!

**Comment by ivan-aksamentov** [comment]
Thanks for trying this @theosanderson !
I think this is the same problem as we have in NExtclade: https://github.com/nextstrain/nextclade/issues/313

This is probably due to `node_modules/.bin/next`  being called directly, 
which is Linux specific. On windows it should probably call something else.

The reason for calling `node_modules/.bin/next` is that we need `next.config.js` to be transpiled, so we run `babel-node` and need to pass the filepath to the script. In normal circumstances when using Next.js you just run `next`. Which probably resolves to something other than `node_modules/.bin/next` on Windows (`node_modules/.bin/next.bat` maybe?)

We could either fix this `dev` script or introduce something separate, Windows-specific, like `dev:win`.


The truth should be somewhere in
https://github.com/vercel/next.js/
probably in
https://github.com/vercel/next.js/tree/canary/packages/next

In any case, Emma was able to run `yarn dev` on WSL. So we could document that.


I'm distracted now and don't have a Windows machine handy. If you have time to dog into this, please do! That would fix two repos.

Otherwise, if someone stumbles upon it, contributions welcome!

**Comment by emmahodcroft** [comment]
@theosanderson I'm sorry you're having trouble and we weren't able to fix! If you have Windows Subsystem for Linux - that's what I've been running this in and it works well. You might want to give it a try there!

**Comment by theosanderson** [comment]
No worries - I got things going fine on a Mac regardless!

So Ivan, I have a `./bin/next.cmd` file which looks like it's the right thing, contents:
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\next\dist\bin\next" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\next\dist\bin\next" %*
)
```

but if I (temporarily) swap out `./bin/next` for `./bin/next.cmd` in `package.json` I get

```
$ cross-env NODE_ENV=development BABEL_ENV=development NODE_OPTIONS=--max_old_space_size=8192 babel-node --extensions ".js,.ts" -- node_modules/.bin/next.cmd dev --hostname 0.0.0.0 --port 3000
C:\users\theo\cov2\cluster_scripts\web\node_modules\.bin\next.cmd:1
@IF EXIST "%~dp0\node.exe" (
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\Users\Theo\cov2\cluster_scripts\web\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at Object.<anonymous> (C:\Users\Theo\cov2\cluster_scripts\web\node_modules\@babel\node\lib\_babel-node.js:180:21)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
```
    
    So I guess whatever is running it isn't expecting to see `.cmd` files. This isn't a big issue for me at all, just documenting it in case we were able to easily solve it for everyone. If I make any more progress I'll let you know but will probably go with other solutions. Thanks for all the help.

**Comment by theosanderson** [comment]
(Similarly tried )
```
$ cross-env NODE_ENV=development BABEL_ENV=development NODE_OPTIONS=--max_old_space_size=8192 babel-node --extensions ".js,.ts" -- node_modules/next/dist/bin/nest dev --hostname 0.0.0.0 --port 3000
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'C:\users\theo\cov2\cluster_scripts\web\node_modules\next\dist\bin\nest'
```

Although the file does exist afaict. (as you can tell I'm in over my head)

**Comment by theosanderson** [comment]
I think I've got it, sorry for the running commentary. PR soon.
