### ISSUE TITLE
Gene name in the list of Nonsynonymous defining mutation

### ISSUE THREAD

**Issue by gyanmishra** [hodcroftlab/covariants#185]
Hi, 

I see the gene name 'ORF1b' in the list of Nonsynonymous defining mutation section. Is that correct?

**Comment by emmahodcroft** [comment]
Hi @gyanmishra - yes, that's correct. We use the same gene annotation as on Nextstrain - you can see the genome a little down the page here: https://nextstrain.org/ncov/global
![image](https://user-images.githubusercontent.com/14290674/123304537-56afdb00-d51f-11eb-82b6-cb11cb7ebc57.png)

However, if you think we've gotten a mutation wrong, or something else looks amiss, let me know with a link and a screenshot and I'll try to fix it!
