### ISSUE TITLE
Filter for representative sample

### ISSUE THREAD

**Issue by rafalopespx** [hodcroftlab/covariants#204]
Hi there, amazing work!

So, I am Brazilian researcher on drivers of epidemics dynamics, and one the things we try to do is to estimate some parameters to new strain coming, for example, one the first thing we ask for is a representative sample for the data frequencies. 

To illustrate, since last week, plots from Covariants.org were used to say that Brazil is nowadays dominated by Delta VOC, but as our genomic surveillance is not real-time, as more sequences are deposited to Gisaid, the prevalence and consequently which strain is dominating is always alternating.

My suggestion is to give an option to filter the plots, say per country or per variant, if marked, to show only those places which has representative samples of the total cases or total population. 
A very rough approximation would be just take the whole amount of sequences, in a given date, and divide it by the population and/or by the amount of case confirmed on this date. 
The first is only a constant dividing the size of the sample, the last is a little bit more complex, but totally workable to you guys.

Thanks for the work! Stay Safe!

**Comment by rafalopespx** [comment]
Hey there!

Just to post you guys on the debate of genomic surveillance in Brazil, this letter (https://www.sciencedirect.com/science/article/pii/S2667193X21000910) has just been published on The Lancet Regional Health - Americas

I highlight the following part:

"According to data from GISAID, that institution submitted 6,528 sequences to the database up to last August 26. When this number is compared to an epidemiological bulletin on their site, where it is stated that until the 32nd epidemiological week 19,185 samples were sequenced, we observe almost 2/3 of their sequences have not been submitted to GISAID. 
Considering Brazil has submitted 31,826 sequences, something like 40% of Brazilian sequences are not on the platform, and it could be possible that other institutions may do the same. If we consider São Paulo State’s reality, which sequences more than 1/3 of samples in Brazil, it causes a severe impact to the country, although there is state regulation from SES-SP that
demands the GISAID accession number for the confirmation of variant cases in the territory."

bests!
Thanks for the amazing site and work!

**Comment by emmahodcroft** [comment]
Thanks for letting us know about this article! It's absolutely important to keep these types of things in mind when looking at sequences - and remembering what biases might be caused if they're not evenly submitted. I had no idea that so many Brazilian sequences were not making it online. Do you have any idea why?

**Comment by rafalopespx** [comment]
Politics, basically. Instituto Butantan, is one of the most respectful scientific institution on Brazil, but just after the election of São Paulo State governor and due to the pandemics, the institute was turned into a merely platform to promote the governor. They still do a good scientific work and they are still respectful as an institution, but some decisions, like to post the sequences generated on GISAID are being guide primarily by politics and not by scientific interest.

I would say that they probably have a complete genomic surveillance study set and being run, and maybe this why they are keeping those sequences out of GISAID. I think the answer here is public and civic pressure, as like was stated by the authors of the letter, which are from another very scientific respectful institution. The Instituto Adolfo Lutz, is the responsible for the sequencing and genomic surveillance for the São Paulo State and part of the Southeast region of Brazil. but as was stated in the letter part of this work is being made by the Instituto Butantan.

Sorry to not have any other good information to give, but I think this what it is in our times, unfortunately.

Again, thanks a lot for the work! I really love the CoVariants.org.
