### ISSUE TITLE
Week Field: Start or End?

### ISSUE THREAD

**Issue by CarloGraziani** [hodcroftlab/covariants#213]
### Discussed in https://github.com/hodcroftlab/covariants/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **CarloGraziani** August 31, 2021</sup>
Hello.

(1) Thanks for assembling and curating this data. It's crucial to something we're working on (we will follow the citation guidelines described in your FAQ of course).

(2) In the file cluster_tables/USAClusters_data.json, does the "week" array refer to the beginning of the reporting period, or to the end? In the case of the delta variant, the advent of prevalence in the USA was so rapid that it actually can matter quite a bit which interpretation is correct.

Cheers,

Carlo</div>

**Comment by emmahodcroft** [comment]
Hi Carlo!

Thanks for your kind words and I'm so glad it's useful! I'd be curious to know what you end up with :)

For all the dates in the data files, the date is always the 'start' of the period. I hope that helps!

**Comment by CarloGraziani** [comment]
Thanks, Emma. Writing it up now.  I'm a bit puzzled about acknowledgment, actually. I see the FAQ request for

"Emma B. Hodcroft. 2021. "CoVariants: SARS-CoV-2 Mutations and Variants of Interest." https://covariants.org/"

which I am of course happy to do. I am confused about my obligations with respect to GISAID, though. Also, I actually used the USAClusters_data.json file, from github, so perhaps I should also cite the github repo? 

Please let me know what your preference is.
