### ISSUE TITLE
Add "installation prerequisites" file for people unfamiliar with CI tools

### ISSUE THREAD

**Issue by tatzelbrumm** [hodcroftlab/covariants#225]
Please consider adding a file that lists **all** the tools, scripting languages, and abstraction layers that you implicitly take for granted, but are at least an order of magnitude harder to parse and understand for potential contibutors unfamiliar to them than your own programs,

and please add links to documentation of these tools, scripting languages, and abstraction layers that explain how to install them on one's own computer.

![The beginner should not be discouraged if he finds he does not have the prerequisites for reading the prerequisites.](https://i0.wp.com/boffosocko.com/wp-content/uploads/2010/09/71naT3Lwi0L.jpg)

**Comment by emmahodcroft** [comment]
Hi @tatzelbrumm  - thanks very much for your suggestion. As you might know, we are a very, very small organization - I maintain CoVariants as much as I can around my research, and @ivan-aksamentov steps in when he can help, from his full time job with another lab. However, I know it's frustrating when trying to get something to work, and the prerequisites aren't so easily defined. @ivan-aksamentov can we keep this in mind as something to check over when we have some time in the future?
