### ISSUE TITLE
21K / B.1.1.529 : who_name → Omicron

### ISSUE THREAD

**Issue by jcahill** [hodcroftlab/covariants#226]
B.1.1.529 has been designated by TAG-VE on 2021-11-26.  
Label updates seem to be via hand-editing of `clusters.py`…  
But I don't want to needlessly muck it up with a hasty PR.  

Additionally, there are some considerations regarding lay names:
- "South Africa variant" redux
- Presumptive use of "Nu" in news media in 2021-11

https://www.who.int/news/item/26-11-2021-classification-of-omicron-(b.1.1.529)-sars-cov-2-variant-of-concern

**Comment by rajivshah3** [comment]
I included the "Omicron" naming in #228 but I'm not entirely sure what to do about the lay names

**Comment by emmahodcroft** [comment]
Thank you for this! I've incorporated these into the webpage. I didn't want to encourage geographic naming, so I've left this out. Do you have a twitter I can tag @jcahill ?

**Comment by jcahill** [comment]
[**@emmahodcroft**](https://github.com/emmahodcroft) commented on [2021-11-27 14:16](https://github.com/hodcroftlab/covariants/issues/226#issuecomment-980787785 "2021-11-27T19:16:27Z - Replied by Github Reply Comments"):
> Thank you for this! I've incorporated these into the webpage. I didn't want to encourage geographic naming, so I've left this out. Do you have a twitter I can tag [@jcahill](https://github.com/jcahill) ?

A twitter? My group's is https://twitter.com/metamerlabs

As for lay names: they're very much a secondary concern. I think the maximal case for rendering them would be as something like footnotes or all together on one discrete page.

Whether [ non-scientific name → scientific name ] mappings provide any additional value seems to rest on whether covariants' target audience can be expected to require such disambiguation.

Whether *mistaken reporting of* scientific/sci-comm names bears consideration is a bit more complex. TAG-VE hasn't provided a list of greek letters it intends to skip, so we may see this crop up as a repeat issue in media.

**Comment by emmahodcroft** [comment]
Hi @jcahill  - thank you! I'm afraid I already tweeted, but I'm still glad to know your twitter!

Yes, at the moment the name information is at the bottom, but as you say, it's worth including to help explain this, especially since there was some confusion.
