### ISSUE TITLE
Integrartion with Chilean official database

### ISSUE THREAD

**Issue by MinCiencia** [hodcroftlab/covariants#229]
Hi, thanks your all your work and kudos for the great results you've accomplished. We keep track of covid19 in chile thorugh our official github site, would like to use your gisaid integration to add a dataproduct related with coviarants, info we are currently not including. Is it possible to get any direction on how to do this?

This is our current repo github.com/MinCiencia/Datos-COVID19

**Comment by emmahodcroft** [comment]
Hi @MinCiencia ! Yes, you're welcome to use the aggregated data from CoVariants to plot your own graphs or use for your own analysis. You can find the data behind the graphs on the "Per Country" page [here](https://github.com/hodcroftlab/covariants/blob/master/web/data/perCountryData.json) and the data from the "Per Variant" graphs [here](https://github.com/hodcroftlab/covariants/blob/master/web/data/perClusterData.json). For example, if you wanted to replicate the Chilean plot, you can search the first file for Chile and should find all the numbers you need there. Please do cite and link back to CoVariants and acknowledge GISAID!

**Comment by MinCiencia** [comment]
Hi again, @emmahodcroft, we are interested in understanding how to extract data from gisaid, where is the code that creates these json from there?

**Comment by emmahodcroft** [comment]
Hi @MinCiencia - it is possible to generate this from GISAID, but it's quite a long process. First, the starting data is a bulk download from GISAID, which requires API access (you would need to discuss this with them). Then, it has to be run through the `ncov-ingest` pipeline ([link](https://github.com/nextstrain/ncov-ingest)), and `ncov` pipeline ([link](https://github.com/nextstrain/ncov)) preprocessing steps to the point of getting the starting files - `metadata.tsv` and `mutation_summary_gisaid.tsv` - from there you can run the code in this repository. 

Alternatively you could download the entire metadata  file from GISAID, and use `ncov` to adjust the header format (there's a `sanitize_metadata` call one could copy). Then download all the sequences, and run the `build_mutation_summary` step from `ncov` to generate the mutation summary file - these could probably work as starting points as well.

I'm sorry it's not more straightforward!

**Comment by MinCiencia** [comment]
All right, any recommendation on how to work with the json you produce, then? We would like to use pandas and filter just Chilean data, haven't had time to look at it in detail yet, but your guidance is appreciated.

**Comment by emmahodcroft** [comment]
Hi @MinCiencia - yes, it shouldn't be too hard to get the data you need. It's a standard JSON so there are a few different python options for opening it up - then you can look for the 'Chile' entry, and you should find the lists of dates, total sequences & sequences for each type of variant - these should let you replicate the graphs! I don't have any code that does this myself, but it shouldn't be too complicated to extract what you need :)
