### ISSUE TITLE
New omicron cases detected in different countries

### ISSUE THREAD

**Issue by Amin-Sharifan** [hodcroftlab/covariants#235]
Hello everyone! 

I was not quite sure how to deliver this message but I thought this might be the best option for me to update the existing knowledge regarding the Omicron status around the world. 

As you may know, Omicron variant is circulating around the world and new cases are being identified. I'm adding the links that have new information regarding the detection of the new cases so that you could update the map regarding the prevalence of this variant. 
https://www.cdc.gov/media/releases/2021/s1201-omicron-variant.html

Here is also a link to the more updated version of the global prevalence:
https://www.cnbc.com/2021/12/02/interactive-map-shows-where-the-covid-omicron-variant-has-been-detected.html

Be safe!
Amin

**Comment by emmahodcroft** [comment]
Dear @Amin-Sharifan - thanks so much for the links! In general though, I try to link to things that are more globally focused, and likely to be longer lasting (I don't know how long CNN will keep this link updated). If you know of any good maps showing cases worldwide from places like CDC, ECDC, WHO, or other academic/international organizations, please let me know and I might include them!

**Comment by Amin-Sharifan** [comment]
Hi @emmahodcroft. I was surfing the net and found this link: https://www.gisaid.org/hcov19-variants/.
Do you think it could be useful to provide additional information regarding different variants?

**Comment by emmahodcroft** [comment]
HI @Amin-Sharifan Thanks for the link! There are a few different website out there that track variants, I'm hesitant to link to one without feeling like I should link to them all! :)
