### ISSUE TITLE
Feature: Whole-world variant proportions graph

### ISSUE THREAD

**Issue by BioTurboNick** [hodcroftlab/covariants#252]
Like the per-country graphs, but incorporating the whole world. Perhaps normalized by country sequencing counts and population. I'd be curious to see what the global picture is.

**Comment by emmahodcroft** [comment]
Thanks @BioTurboNick !
This is something that's been [suggested by others](https://github.com/hodcroftlab/covariants/discussions/241), however, it is something that's tricky as normalizing by country is not so easy - for many countries in the world we don't have accurate data and so the 'world' view will be dominated by countries for which sequencing is commonplace & made public quickly. 

At the moment I'm not sure that a combined "world" chart would be representative enough to be useful, but I'm happy to continue considering it.

**Comment by BioTurboNick** [comment]
Closing to clean up my dashboard and it's a duplicate :-)
