### ISSUE TITLE
Mutation from variant Omicron 21L "S:G142D" (in /variants) appears as "S:G142-" in (/shared-mutations)

### ISSUE THREAD

**Issue by holalluis** [hodcroftlab/covariants#261]
- in https://covariants.org/variants/21L.Omicron appears "S: G142D"
- in https://covariants.org/shared-mutations appears "S: G142-"

which is the correct one?

thanks!

**Comment by emmahodcroft** [comment]
Hi @holalluis - I responded to your slightly longer post about the error in the shared mutations page - you're right, this should match! The correct is S:G142D.

I'm pushing up a fix now. Do you have a twitter handle for credit?

**Comment by holalluis** [comment]
Great! Thank you for the quick fix. My twitter is https://twitter.com/holalluis
