### ISSUE TITLE
Mutations "S:V143-", "S:Y144-" and "S:Y145D" from variant Omicron 21L appear at "/shared-mutations" but not in "/variants"

### ISSUE THREAD

**Issue by holalluis** [hodcroftlab/covariants#262]
screenshot from https://covariants.org/variants/21L.Omicron
![image](https://user-images.githubusercontent.com/1082644/149405143-2b0604e7-2550-4ec4-b0d5-9dad5ea3a7ca.png)

screenshot from https://covariants.org/shared-mutations
![image](https://user-images.githubusercontent.com/1082644/149405210-49e249ca-907e-4734-980b-43a3a69fe595.png)

(I've reported the difference in "S:G142?" in a previous issue)

**Comment by emmahodcroft** [comment]
Hi @holalluis - Thank you so much for spotting this error! You're right, this is not in there correctly, and I appreciate you letting me know!

The current 21L variant page is correct - there is a mutation at S:G142D but there are not deletions, nor a mutation at S:Y145. I must have mixed things up while transcribing.

I'm pushing up a fix for this now, and it should make the shared mutations and 21L page match - but please do let me know if you spot any other errors!

**Comment by holalluis** [comment]
Thank you for the fix! I'll let you know if I find any other issue! :)
