### ISSUE TITLE
How to download representive sequence of 20A.EU1 in 20A.EU1_table.tsv

### ISSUE THREAD

**Issue by wanglu2014** [hodcroftlab/covariants#265]
In \cluster_tables directory, there were many tsv files, such as 20A.EU1_table.tsv.
If we want to get the representative sequence of 20A.EU1 , could you kindly suggest how to download the representative sequence?
Some people believe the first strain which identified in this clade was the representative sequence. Is it the first identified strain was  the representative sequence of your table?

**Comment by emmahodcroft** [comment]
Hi @wanglu2014 , thank you for your message! I'm afraid I don't keep track of any representative sequences. In general, to get the mutation list, I choose a sequence as close to the base of the variant as possible. If it's right at the base of the cluster, then I take all those mutations. However, if there is no sequence at the base (not uncommon), I find one as close as possible, and remove any mutations which are between the variant base and the sequence.

Hopefully this helps you to identify your own representative samples!

**Comment by wanglu2014** [comment]
Thank you for your reply!
