### ISSUE TITLE
How to extract all the mutation and its position on a sequence?

### ISSUE THREAD

**Issue by wanglu2014** [hodcroftlab/covariants#266]
I known some tools such as mafft can analysis and extract mutation position. Since you have a well-curated mutation database, could you kindly share with me? 
Email: wanglu2014@sibcb.ac.cn

**Comment by emmahodcroft** [comment]
Hi @wanglu2014  - probably the easiest way to get mutations is to use [Nextclade](https://clades.nextstrain.org/). Here, you can quickly upload any sequence or set of sequences, and it will tell you mutations. You can access this through the visualization or there are many options for downloading the output files. Alternatively, there is a CLI version you can download and run locally if you want to process a lot of sequences.

**Comment by wanglu2014** [comment]
Thank you for your timely reply!

**Comment by wanglu2014** [comment]
Dear Dr. Hodcroft, my goal is track the evolution path according to the mutation listed in your distinguishable study. It is a general evolution path, not for some specific sequence and strain. Could kindly suggest how to directly download the mutation in your website.
