### ISSUE TITLE
Which algorithm you used to infer the parent/child relationships between different clades?

### ISSUE THREAD

**Issue by wanglu2014** [hodcroftlab/covariants#268]
![image](https://user-images.githubusercontent.com/12541282/150681319-c826e7a1-1dc6-4072-95ee-fefc3f1858f1.png)
Your visualization is pretty, could you kindly suggest how you infer their parent/child relationships? Related code or paper will be a great help!

**Comment by emmahodcroft** [comment]
Hi @wanglu2014 - thank you, I'm glad you like it!
This graph comes from https://github.com/nextstrain/ncov-clades-schema which is part of Nextstrain. 

The relationships are entered manually here: https://github.com/nextstrain/ncov-clades-schema/blob/master/src/clades.json

But these are derived from looking at the phylogenetic relationships in the Nextstrain trees - you can see them generally [here](https://nextstrain.org/ncov/gisaid/global), but note that from run-to-run we do sometimes have issues with clades being in the right place. However, from studying the sequences throughout the pandemic we are quite confident in their relationships, so this is a simpler schema showing this.
