### ISSUE TITLE
Incorporate strong MHC binders graph

### ISSUE THREAD

**Issue by koratkar** [hodcroftlab/covariants#269]
There are software projects that predict MHC binders when given a sequence and an HLA. What might be interesting is plotting the average number of strong binders among several different popular HLA types over time for each variant. This could be done by making a graph for each variant, and plot each significant mutation's binders on the Y axis. 

Some issues are that this might be a bit outside the scope of CoVariants and the software used to make these predictions is mostly machine learning based and not completely accurate.

**Comment by emmahodcroft** [comment]
Hi @koratkar, thanks for posting! I agree that looking at HLA binding strength to different epitopes with different mutations is really interesting. However, I think, as you say, this may be beyond the scope of CoVariants. This is type of thing I'd be happy to consider linking or embedding if someone else is providing it in a standardized way though, so please feel free to make a PR or suggestion if you know of such sources!
