### ISSUE TITLE
Clarify protein model on variant page is S protein

### ISSUE THREAD

**Issue by osirisinferi** [hodcroftlab/covariants#270]
Currently, when viewing a variant, at the bottom of the page a fancy protein is displayed, either static JPEG or animated GIF.

The title and caption respectively currently state:

> Protein model for ${variant}`

and

> Protein model for `${variant}`. Figure made via GISAID

When looking at the proteins on https://github.com/hodcroftlab/covariants/tree/master/web/public/proteins it seems all images are of the S protein.

I recommend adding the distinction to the card that the protein being visualised is the S protein of the virus, as the virus obviously contains many more proteins.

**Comment by emmahodcroft** [comment]
Hi @osirisinferi ! Thanks for drawing this to my attention - you're right! I've just made a change to specify that the protein models are Spike, and as long as this looks good, it should go live next time I update the website. Thanks again!
