### ISSUE TITLE
Allow linking to pages with specific filter set in URL

### ISSUE THREAD

**Issue by osirisinferi** [hodcroftlab/covariants#271]
Might be partly related to #27. Or not.. :stuck_out_tongue: 

Currently, if I look at the https://covariants.org/per-variant page and I set a specific filter (e.g., just a single country), I don't see a way to link to that specific page with that specific filter set.

Maybe something is possible using the [URI fragment](https://en.wikipedia.org/wiki/URI_fragment) part of an URI? E.g., https://covariants.org/per-variant#country=NL or something like that. Using the URI fragment would require client-side coding. I don't know if that's easier than using server-side coding e.g. https://covariants.org/per-variant/country=NL.

**Comment by emmahodcroft** [comment]
HI @osirisinferi ! Thanks for the issue - you're right, this is what we hope to achieve with #27!

I completely agree that this would be fantastic to have. There's been a little work on it in #240 but that may have stalled. We'd really welcome anyone willing to work on this issue!

**Comment by osirisinferi** [comment]
@emmahodcroft I'm closing this as a duplicate in favor of #30 (that issue is a little bit more specific, #27 is more about when people are navigating the site I think. Although both can of course be combined.). While I did look at the open issues, it seems I've missed that one, sorry!
