### ISSUE TITLE
Can you offer the download link for the historical data?

### ISSUE THREAD

**Issue by lzxiaohu** [hodcroftlab/covariants#277]
Hi, 

Thanks for your work. Can you offer historical data about proportion of variants?

**Comment by ivan-aksamentov** [comment]
Hi @lzxiaohu,

There is no download link and the project team does not currently have resources to support this use-case. But you can probably adapt the data that is used by the web app. It is in the `web/data` directory:
[github.com/hodcroftlab/covariants/tree/master/web/data](https://github.com/hodcroftlab/covariants/tree/master/web/data)
You care probably interested in `perClusterData.json` or `perCountryData.json`.
