### ISSUE TITLE
URLs not working on 'Cases' page

### ISSUE THREAD

**Issue by emmahodcroft** [hodcroftlab/covariants#299]
URLs on Per Country and Per Variant pages allow the URL to modify if users specify particular countries/variants. This should work the same on the Cases page. Indeed, selecting countries does change the URL at the top (and view). However, when putting that URL in a new window, it doesn't actually filter to just showing what's in the URL.

Compare URLS:

On Cases page:
https://covariants.org/cases?country=USA&country=Canada&country=Japan&country=Croatia Should show:
![image](https://user-images.githubusercontent.com/14290674/164761223-f5abcd72-3a44-4005-81e6-d79fe0f86cab.png)
(but shows all countries)

But on Per Country Page:
https://covariants.org/per-country?country=USA&country=Canada&country=Japan&country=Croatia
Works as expected and shows:
![image](https://user-images.githubusercontent.com/14290674/164761391-c006fdc6-502d-444a-9aa4-13dfd4fad544.png)

It also doesn't work on Cases page for variants:
https://covariants.org/cases?variant=21A+%28Delta%29&variant=21I+%28Delta%29&variant=21J+%28Delta%29

I'm hopeful this is just a plumbing issue - the 'Cases' page just wasn't fully hooked up into the URL system, and can be without too much work!

**Comment by ivan-aksamentov** [comment]
Should be resolved in #300
