### ISSUE TITLE
Add BA.2.9 alias for B.1.1.529.2.9 to covariant website

### ISSUE THREAD

**Issue by summercms** [hodcroftlab/covariants#310]
Would it be a good idea to add BA.2.9 

As of (today) has 349851 total sequences so far and in many countries.

I believe European Centre for Disease Prevention and Control labels it as a **Variant under monitoring**, checked [WHO](https://www.who.int/activities/tracking-SARS-CoV-2-variants) and [UK Gov](https://www.gov.uk/government/publications/covid-19-variants-genomically-confirmed-case-numbers) websites (they seem to be slow and not yet mention it).

Maybe you can add it or monitor it, because it has a 19.29% overall proportion to the world and so I thought I'd mention it as it's over 10%.

Links:

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.2.9&

https://github.com/cov-lineages/pango-designation/issues/530

**Comment by emmahodcroft** [comment]
Hi @summercms - thanks for alerting me to this. This variant is indeed interesting. However, it differs only by [1 AA mutation in ORF3a](https://github.com/cov-lineages/pango-designation/issues/432) as far as I can tell, and I'm not sure if this is just being pulled up by the spread of BA.2.

Currently with so many lineages going around, I'm trying to keep adding things to CoVariants that are likely of more specific interest, such as potential (or known) differences in transmission, immunity, etc. But, I'm happy to keep an eye on this, or a potential sublineage of this, if it seems like it becomes worth designating!

**Comment by summercms** [comment]
@emmahodcroft I let you decide if you want to close this issue, it seems like **BA.2.9** numbers are declining quite quickly and **BA.2.12.1** and **BA.2.10** are taking over.

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.2.12.1& 

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?pangoLineage=BA.2.10&

As you said it differs only by one AA mutation, so it's probably not wise to add it to CoVariants (as you guys seem to add variants with much more mutations).
