### ISSUE TITLE
Omicron in Israel in 2020

### ISSUE THREAD

**Issue by yuval-harpaz** [hodcroftlab/covariants#318]
Displaying only [recent variants](https://covariants.org/cases?country=Israel&variant=21L+%28Omicron%29&variant=22A+%28Omicron%29&variant=22B+%28Omicron%29&variant=22C+%28Omicron%29) I was surprised to see a bump in Oct 2020. Is this a bug? Or is it an early version of Omicron somehow tracked by the system?
It seems to come from [this](https://raw.githubusercontent.com/hodcroftlab/covariants/master/web/data/perCountryDataCaseCounts.json) json, look up Israel, 12 Oct 2020 (1340 cases)
![image](https://user-images.githubusercontent.com/445416/173771066-65553ce0-0fc4-40dd-b562-edda9491a8c6.png)

**Comment by yuval-harpaz** [comment]
Hi, after the update, the culprit is still there. Please see the following segment in [perCountryDataCaseCounts.json](https://raw.githubusercontent.com/hodcroftlab/covariants/master/web/data/perCountryDataCaseCounts.json)
            },
            {
              "percent_total_cases": 0.0002140983782047851,
              "stand_estimated_cases": {
                "20A.EU2": 0,
                "20A/S:439K": 0,
                "20A/S:98F": 0,
                "20B/S:732A": 0,
                "20E (EU1)": 0,
                "20H (Beta, V2)": 0,
                "20I (Alpha, V1)": 0,
                "20J (Gamma, V3)": 0,
                "21A (Delta)": 0,
                "21B (Kappa)": 0,
                "21C (Epsilon)": 0,
                "21D (Eta)": 0,
                "21G (Lambda)": 0,
                "21H (Mu)": 0,
                "21I (Delta)": 0,
                "21J (Delta)": 0,
                "21K (Omicron)": 0,
                "21L (Omicron)": 0,
                "22A (Omicron)": 1005,
                "22B (Omicron)": 0,
                "22C (Omicron)": 502,
                "others": 503
              },
              "stand_total_cases": 2010,
              "total_sequences": 4,
              "week": "2020-10-12"
            },
![image](https://user-images.githubusercontent.com/445416/177148791-0f614a9c-9765-4aca-a06e-b77d35671101.png)

**Comment by emmahodcroft** [comment]
Hi @yuval-harpaz - just to let you know, the new update is now live, and the offending sequences should be gone! Thanks again for alerting me to it!

**Comment by yuval-harpaz** [comment]
Perfect, thanks. [Here](https://twitter.com/yuvharpaz/status/1543981168541982720?s=20&t=m3Ci1EFBS3CWf6qxYF8RlQ) is another thanks on twitter.
