### ISSUE TITLE
How to show the proportion for each clade? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [hodcroftlab/covariants#322]
Dear Emma, 
If there any way to show the proportion, rather than the case number? for example, given any timepoint, delta is 80%, beta is 5% etc.. (sum is 100%). 

Thanks. 

Shicheng

**Comment by emmahodcroft** [comment]
Hi Shicheng,
Thanks for writing! The page that will show the proportion rather than count is the Per Country page: https://covariants.org/per-country

I hope this has what you were looking for!
Best wishes,
Emma
