### ISSUE TITLE
Total cases inconsistent with JHU report

### ISSUE THREAD

**Issue by yuval-harpaz** [hodcroftlab/covariants#329]
This may be my misunderstanding, but I cannot match the total variant count with the number of cases reported by JHU / OWID. Here we see that the peak for Singapore and Italy was around 3000 cases per million a day, while the variant count peaked to ~45k per million (daily? weekly?)
![image](https://user-images.githubusercontent.com/445416/178084964-f6a5a6b6-1303-4976-a2b4-b444a44a9b79.png)

![image](https://user-images.githubusercontent.com/445416/178084851-4d476099-afea-41ae-b03c-b6547953626c.png)

**Comment by yuval-harpaz** [comment]
Another look just to confirm that the case count in my plots reflects JHU data
![image](https://user-images.githubusercontent.com/445416/178083114-e9d158ab-6767-4695-a8b2-e689bc0945a3.png)

**Comment by yuval-harpaz** [comment]
Ah, cases per million people, my bad.

**Comment by emmahodcroft** [comment]
Hi @yuval-harpaz - apologies for all the confusion here! The big difference here is that the JH data (and the OWID data) give daily numbers, but for CoVariants, we use a 2-week period (you can see what this is by mousing over a period on the plot). This should reconcile the numbers - if a place has 3000 cases a day, in CoVariants that would be 42,000 for the two-week period (and assuming it was sometimes higher than 3000, I imagine we hit matching numbers).

I hope this clarifies the discrepancy!

**Comment by yuval-harpaz** [comment]
yes, all clear now, thank you
![image](https://user-images.githubusercontent.com/445416/178102492-9eb641f4-c9ee-4933-b215-29fb037c6c2e.png)
