### ISSUE TITLE
Shared aa substitutions vs. shared nucleotide mutations

### ISSUE THREAD

**Issue by robertw-hihm** [hodcroftlab/covariants#345]
The table on https://covariants.org/shared-mutations shows the shared aa substitutions caused by shared nucleotide mutations; amino acids aren't subject to mutation, only nucleotide sequences. It would be very helpful for a similar table that depicts the latter, using coordinates from a single ancestral SARS CoV-2 nucleotide sequence that is also made available via its accession number or a fasta file. Thanks!

**Comment by emmahodcroft** [comment]
Hi @robertw-hihm - thanks for reaching out!  Currently on our shared-mutations table we only show the differences in amino-acids between the variants, as these are generally what's been of most interest.
I would love to extend this to other proteins, and potentially find ways to expose the underlying mutations, but unfortunately it hasn't been possible to integrate this yet (though contributions are always welcome!).

You can find, for a few of the variants, machine-readable files that list all mutations, including linking nucleotide to AA changes, in [this folder](https://github.com/hodcroftlab/covariants/tree/master/defining_mutations). Unfortunately I haven't been able to generate these files further back than Omicron - but perhaps they can still be of some help!

All coordinates are relative to the ancestral Wuhan strain ("Wuhan-Hu-1")

**Comment by robertw-hihm** [comment]
Dear Emma,

Thanks very much for the link to the defining mutations folder and for informing me of the ancestral "Wuhan-Hu-1" strain to be used as reference. As you can guess, I’m not a COVID expert, or even a virologist, but rather a general molecular geneticist/biologist and a self-taught bioinformatician over many years (from when we performed BLAST searches by ftp in the late 1980s/ealry90s). My interest in the variants stems from my aim to apply an in-house method for multiplex genotyping of up to 30 SNP-allele variants in a single reaction using common 5-channel QPCR instrumentation and I therefore need to nucleotide substitutions. Luckily, the information as far back as Omicron will provide me with most of what I need as most of their mutations are shared backwards in time.

Thanks again.

Kind regards,
Rob Wilson
Professor of Molecular Biology
Department of Biotechnology
INN University
Phone: +47 95 04 91 96
E-mail: ***@***.******@***.***>
Visiting address: Office 245, Biohus, Holsetgate 22, Hamar, NORWAY
Mailing address: PO Box 400, NO-2418 Elverum, NORWAY
Website: eng.inn.no<http://eng.inn.no> (English); www.inn.no<http://www.inn.no/> (norsk)


Fra: Emma Hodcroft ***@***.***>
Dato: fredag, 2. september 2022 kl. 11:28
Til: hodcroftlab/covariants ***@***.***>
Kopi: Rob Wilson ***@***.***>, Mention ***@***.***>
Emne: Re: [hodcroftlab/covariants] Shared aa substitutions vs. shared nucleotide mutations (Issue #345)

Closed #345<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhodcroftlab%2Fcovariants%2Fissues%2F345&data=05%7C01%7Crobert.wilson%40inn.no%7C27d1b1efab5f4d057e6a08da8cc57d02%7Cd45cfa45904a497297413335dc0372b4%7C0%7C0%7C637977077086862181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wfad7thB1oXxTVFGAovV2Nc1gXYvABxoVpOvD2NtyGA%3D&reserved=0> as completed.

**Comment by robertw-hihm** [comment]
Hi Emma,

Do you have the spike gene reference sequences of the variants listed below?

If not, do you know where I can retrieve these sequences, short of deciphering them from the primary literature?

Many thanks.

Best,
Rob

BA.2.75.2
BA.4.6.3
BA.5.1
BE.1.1
BE.4.1
BE.7
BF.5
BF.7
BF.11.2
BF.26
BM.1.1.3
BN.1
BQ.1
BY.1.1.1
CH.1.1
CJ.1
CK.2.1.1
CN.1
CQ.1
DF.1
XBB.1


Fra: Emma Hodcroft ***@***.***>
Dato: fredag, 2. september 2022 kl. 11:28
Til: hodcroftlab/covariants ***@***.***>
Kopi: Rob Wilson ***@***.***>, Mention ***@***.***>
Emne: Re: [hodcroftlab/covariants] Shared aa substitutions vs. shared nucleotide mutations (Issue #345)

Hi @robertw-hihm<https://github.com/robertw-hihm> - thanks for reaching out! Currently on our shared-mutations table we only show the differences in amino-acids between the variants, as these are generally what's been of most interest.
I would love to extend this to other proteins, and potentially find ways to expose the underlying mutations, but unfortunately it hasn't been possible to integrate this yet (though contributions are always welcome!).

You can find, for a few of the variants, machine-readable files that list all mutations, including linking nucleotide to AA changes, in this folder<https://github.com/hodcroftlab/covariants/tree/master/defining_mutations>. Unfortunately I haven't been able to generate these files further back than Omicron - but perhaps they can still be of some help!

All coordinates are relative to the ancestral Wuhan strain ("Wuhan-Hu-1")
