### ISSUE TITLE
clade 23A

### ISSUE THREAD

**Issue by patvalcom** [hodcroftlab/covariants#370]
Hi,
I d'ont know if you are already aware of that but on friday I saw the new clade 23A but when I clicked on it it send me the following error message : "Application error: a client-side exception has occurred (see the browser console for more information)." IT is still the case this morning.
Is there something I can do to change that or is it up to you?
Thanks a lot
Patricia

**Comment by emmahodcroft** [comment]
Hi Patricia,
My apologies about this - this was a bug that was inadvertently introduced while trying out some new code, and shouldn't have made it to master! I've pushed a fix and this should be gone within a few minutes :)
Thanks for letting us know about this, so we could fix it - we really appreciate it!
Best wishes,
Emma

**Comment by patvalcom** [comment]
Hi, does it means that the clade 23A does not exist ? I thought it did exist but that only the link was not working!

**Comment by emmahodcroft** [comment]
Hi Patricia,
Yes at the moment there is no clade 23A! Apologies for the confusion!

**Comment by patvalcom** [comment]
No problems!
Thanks for your quick answers!
Patricia
