### ISSUE TITLE
Covid-19 cases graphs are displayed incorrectly

### ISSUE THREAD

**Issue by keepgoing1995** [hodcroftlab/covariants#389]
The graphs showing the number of cases by variant have been inaccurate since the March 6th update.

**Comment by ivan-aksamentov** [comment]
Hi @keepgoing1995,

Thanks for the report!

I see that plots inded look different. But could you please elaborate what you mean by "displayed incorrectly" or "inaccurate". Just to make sure we are on the same page and that we don't miss any other issues if there's multiple.

**Comment by keepgoing1995** [comment]
> Hi @keepgoing1995,
> 
> Thanks for the report!
> 
> I see that plots indeed look different. But could you please elaborate what you mean by "displayed incorrectly" or "inaccurate"? Just to make sure we are on the same page and that we don't miss any other issues if there's multiple or if the displayed information looks different on different systems.
> 
> I'd like to know what is your expectation and what you see instead.

The estimated number of cases looks different from the data provided by OWID. https://ourworldindata.org/covid-cases 
It's like there are spikes every other week for some reason.

**Comment by keepgoing1995** [comment]
> Hi @keepgoing1995,
> 
> Thanks for the report!
> 
> I see that plots inded look different. But could you please elaborate what you mean by "displayed incorrectly" or "inaccurate". Just to make sure we are on the same page and that we don't miss any other issues if there's multiple or if the displayed information looks different on different systems.
> 
> I'd like to know what is your expectation and what you see instead.

@ivan-aksamentov @emmahodcroft It looks like there was some bug in the data provided by OWID. No action is needed other than just updating.

**Comment by emmahodcroft** [comment]
Hi @keepgoing1995 - apologies for such a slow response! Thank you very much for reporting this and for your information on the transient error on OWID.

As you suspected, updating fixed this, and all should now be as expected on the website! Thank you again for your report of this issue!
