### ISSUE TITLE
Reconsider country sort order in ‚Per country‘

### ISSUE THREAD

**Issue by rasenschachmatt** [hodcroftlab/covariants#74]
The sort order of the countries looks a little arbitrary to me - or I have just not figured out the logic yet.

Suggestions:
- Alphabetical
- By number of sequences (descending)

**Comment by emmahodcroft** [comment]
Thanks for this suggestion @rasenschachmatt ! I agree, the ordering is not intuitive at the moment. I am in the process of changing how this works and it should be updated in the next few days!

**Comment by emmahodcroft** [comment]
Now implemented!

**Comment by rasenschachmatt** [comment]
Thank you @emmahodcroft - also for the additional explanations in the text. Looks good!
