### ISSUE TITLE
Detection of E484K mutation in B.1.1.7 VOC 202012/01

### ISSUE THREAD

**Issue by ayumi-cloud** [hodcroftlab/covariants#79]
Extract:

> The COG-UK dataset (total sequences 214,159) was analysed on 26/01/2021. The spike
protein mutation E484K (found in VOC 202012/02 B1.351 and VOC 202101/02 P1) has
been detected in 11 B1.1.7 sequences. Preliminary information suggests more than one
acquisition event

(The 11 cases are split in two different cities quite far away from each other - Liverpool and Bristol).

Link to paper: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/957504/Variant_of_Concern_VOC_202012_01_Technical_Briefing_5_England.pdf

Wanted to suggest adding the UK variant to the https://covariants.org/variants/S.E484

**Comment by emmahodcroft** [comment]
Thank you @ayumi-cloud ! This was added briefly to the S:501 page in #78  - I'm adding a link to the Nextstrain build filtered to these sequences here, and will also add a link to this information on the S:484 page (as most of the 501Y.V1 sequences don't have this mutation, I fear adding a 501Y.V1 section to the 484 page may cause confusion).
