### ISSUE TITLE
Add RshSTT200, RaTG13 and Pangolin/GD closely related viruses

### ISSUE THREAD

**Issue by ayumi-cloud** [hodcroftlab/covariants#83]
Just a thought it would be nice if you added the `RshSTT200`, `RaTG13` and `Pangolin/GD` closely related viruses (above 95% match).

See picture as example:

![image](https://user-images.githubusercontent.com/57409060/107121460-7ef9ae80-688a-11eb-95a9-74b21eeb0d50.png)

I know these aren't exactly variants - but the genome is very similar and I think it would add value to your website. Also I think the evolution of the virus is equally as important.

For more info see link: https://www.biorxiv.org/content/10.1101/2021.01.26.428212v1.full.pdf

**Comment by emmahodcroft** [comment]
Hi @ayumi-cloud ! Thanks for your suggestion. I agree that it's interesting to consider the differences and similarities between the SARS-like CoVs that are closely related to SARS-CoV-2. However, as they are not SARS-CoV-2, and as we don't get regular sequencing updates from these closely-related relatives, there's not really anything here to 'track' which is the primary purpose of this website. So, I don't think we'll be including them at this time, though of course, it would great if other resources want to pick up other ways for people to explore the similarities & differences!
