### ISSUE TITLE
Consider making `others` area grey not white in per-country plots

### ISSUE THREAD

**Issue by theosanderson** [hodcroftlab/covariants#85]
Small suggestion. In my view the per-country area plots are a bit hard to read visually because it's not clear that the white space represents also represents SARS-CoV2 cases (which makes it seem like it's not a plot of proportions). I think making the "other" slice appear in grey so it is clearly a defined proportion might help with this.

![](https://i.imgur.com/YautFQr.png)

**Comment by emmahodcroft** [comment]
Hi @theosanderson ! Thanks for this suggestion. I agree this might be helpful and assist in clarifying - I am getting some questions about these figures. @ivan-aksamentov would such a shading be difficult to implement?

**Comment by ivan-aksamentov** [comment]
Thanks Theo!

Attempted solution is in #86
