### ISSUE TITLE
Idea: use country flags instead of colored circles in legends

### ISSUE THREAD

**Issue by ivan-aksamentov** [hodcroftlab/covariants#88]
Related: #81 #87

The idea is to use country flag icons instead of colored circles on "Per country" page for plot headings and filtering sidebar.

Originally, the country colors were meant for line plots in "Per variant" page, and they have no significance for the "Per country" page. But it was making sense to also use the same colors in country icons to connect the two pages together.

Now that there are more countries added, some colors started to be duplicated. On "Per variant" page the logical solution was to reuse the line styles to make the countries visually distinct #87. However, it might be confusing to use the same kind of line icons on "Per country" page, which does not have line plots.

This should solve the problem of duplicated colors on "Per country" page.

**Comment by emmahodcroft** [comment]
I agree with you Ivan, that this makes more sense than the colours! I'd be happy if this implemented, though I'd say it's not high priority.
