### ISSUE TITLE
Add `VUI202102/01` and `VOC202102/02` variants

### ISSUE THREAD

**Issue by ayumi-cloud** [hodcroftlab/covariants#91]
Hi,

Today in uk two variants of concern have been reported, below are some details:

**VUI202102/01** is characterised by the presence of the E484K spike protein mutation and a small number of other mutations. It is derived from lineage A.23, which is seen internationally, but the E484K additional mutation on this lineage has only been seen within the UK. It was first identified by Public Health England (PHE) on 10 January, while investigating a cluster of 5 cases linked to members of staff from a hospital in Liverpool. So far, 55 cases of this variant have been found.

**VOC202102/02** is a specific cluster characterised by the presence of the E484K spike protein mutation on the VOC202012/01 SARS-CoV-2 B1.1.7 variant that was first detected in the UK at the end of 2020. Through genomic sequencing and enhanced contact tracing, PHE have so far identified 21 cases of VOC202102/02 across the UK, predominantly centred upon an outbreak in the South West of England.

Both have the E484K, so wondered if you wanted to add it to the E484K page?

Link to article: https://www.gov.uk/government/news/phe-statement-on-variant-of-concern-and-new-variant-under-investigation

Hope it helps.

**Comment by emmahodcroft** [comment]
Thanks for this suggestion @ayumi-cloud !  VUI202102/01 as it is not a VoC, though it's tracked and visible as 20B/S:484K on the dedicated 484 build [see here](https://nextstrain.org/groups/neherlab/ncov/S.E484?c=gt-S_484&f_clade_membership=20B/S:484K). 

Similarly, while we don't yet have any way to label the variants in 501Y.V1 (B.1.1.7) that also have 484, we can see them in the 484 build by colouring by that mutation in the 501Y.V1 part of the tree. [See here](https://nextstrain.org/groups/neherlab/ncov/S.E484?c=gt-S_484&f_clade_membership=20I/501Y.V1&label=clade:20I/501Y.V1). Unfortunately as these are not monophyletic there's not a very good way to label these yet. If one of them grows more significantly than the others, we may label this one.

I hope that helps!
